### ISSUE TITLE
[FEAT] chatGPT로 글 추천

### ISSUE THREAD

**Issue by Hwater00** [umc-hackathon-team-r/BondingWizards_Server#2]
## Description
목적과 성향을 받으면 chatGPT가 글을 생성해줍니다. 
## To-do
- [ ] 프론트에서 입력받는 키워드 , 기준으로 분리
- [ ] service에서 키워드를 문장으로 조립
- [ ] chatGTP에게 질문으로 생성된 글을 프론트에게 전달
